# Generated by Django 5.1.6 on 2025-04-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_quizview"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
