name: Build and deploy Python app to Azure Web App - flipnote-quizzer-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
          echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean static files
        run: |
          if [ -d "staticfiles" ]; then rm -rf staticfiles; fi

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      # Optional: Add step to run tests here
      - name: Run tests
        run: |
          python manage.py test

      - name: Remove virtual environment before packaging
        run: |
          rm -rf venv/

      - name: Create deployment package
        run: |
          zip -r release.zip . -x "*.git*" "*.github*" "__pycache__*" "*.pyc" "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_822E2F4850134DC19B81C6EA82C682FA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6C98EA44A83D4A8FB04AB4FE964666F9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8135AC6EA2AF4EF2BA05355CBC849882 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flipnote-quizzer-backend'
          slot-name: 'Production'